import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.locks.ReentrantLock;

public class Kalapastangan {

    private static final ReentrantLock lock = new ReentrantLock();

        public static void main(String[] args) {
                singSong();
                    }

                        public static void animateText(String text, long delay) {
                                lock.lock();
                                        try {
                                                    for (char c : text.toCharArray()) {
                                                                    System.out.print(c);
                                                                                    System.out.flush();
                                                                                                    Thread.sleep(delay);
                                                                                                                }
                                                                                                                            System.out.println();
                                                                                                                                    } catch (InterruptedException e) {
                                                                                                                                                Thread.currentThread().interrupt();
                                                                                                                                                        } finally {
                                                                                                                                                                    lock.unlock();
                                                                                                                                                                            }
                                                                                                                                                                                }

                                                                                                                                                                                    public static void singSong(String lyric, long delay, long speed) {
                                                                                                                                                                                            try {
                                                                                                                                                                                                        Thread.sleep(delay);
                                                                                                                                                                                                                    animateText(lyric, speed);
                                                                                                                                                                                                                            } catch (InterruptedException e) {
                                                                                                                                                                                                                                        Thread.currentThread().interrupt();
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                        public static void singSong() {

                                                                                                                                                                                                                                                                // SLOW OUTRO – MUSIC SYNC FEEL
                                                                                                                                                                                                                                                                        String[][] lyrics = {
                                                                                                                                                                                                                                                                                    {"Oh, oh-oh-oh", "95"},
                                                                                                                                                                                                                                                                                                {"Oh, ooh", "110"},
                                                                                                                                                                                                                                                                                                            {"Mamamatay akong nakangiti", "75"},
                                                                                                                                                                                                                                                                                                                        {"Kapag Ikaw ang nasa aking tabi", "75"},
                                                                                                                                                                                                                                                                                                                                    {"Mabubuhay akong nagsisisi", "75"},
                                                                                                                                                                                                                                                                                                                                                {"Kapag 'sang araw hindi Kita mapapangiti", "65"},
                                                                                                                                                                                                                                                                                                                                                            {"Kalapastangan ang 'di Ka ibigin", "65"},
                                                                                                                                                                                                                                                                                                                                                                        {"Kalokohan ang 'di Ka isipin", "65"},
                                                                                                                                                                                                                                                                                                                                                                                    {"Kung ang mundo ay biglang gugunawin", "60"},
                                                                                                                                                                                                                                                                                                                                                                                                {"Ikaw ang una kong hahanapin", "65"},
                                                                                                                                                                                                                                                                                                                                                                                                            {"Ooh, ooh", "110"}
                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                            // mas mahahabang pagitan, parang vocal breathing
                                                                                                                                                                                                                                                                                                                                                                                                                                    long[] delays = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            3500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        6200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    9000,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                11800,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            15000,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        18300,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    21500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                24800,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            28200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        32000
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ExecutorService executor = Executors.newFixedThreadPool(lyrics.length);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int i = 0; i < lyrics.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            final int index = i;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        executor.submit(() ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        singSong(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lyrics[index][0],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                delays[index],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Long.parseLong(lyrics[index][1])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                executor.shutdown();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while (!executor.isTerminated()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // wait hanggang matapos ang outro
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
